### ISSUE TITLE
Added AUR package

### ISSUE THREAD

**Issue by devins2518** [Luvella/Bunnyfetch#2]
This is a bit retroactive, but I went ahead and make an [AUR package](https://aur.archlinux.org/packages/bunnyfetch-git/) before realizing that I hadn't asked for approval or permission. Sorry about that. If you are fine with it being up, you might want to add it to the README, however, if you don't want it up, that's totally fine and I'll take it down. Thanks!

**Comment by sammy-ette** [comment]
1. the upstream url is alacritty
2. ive kinda left this just lingering around because i dont want to maintain this rust version (which i plan on rewriting in go) and it also panics if some things are missing
so i'd like u to take it down

**Comment by devins2518** [comment]
1. I am an idiot, I'll change that soon. 
2. I'm willing to maintain it if you aren't able to. I've seen the issues you're referencing to and think I can fix them easily

**Comment by sammy-ette** [comment]
ok im fine with that, so do you want this repo or just a fork and link to that here

**Comment by devins2518** [comment]
This repo is fine

**Comment by sammy-ette** [comment]
added you, now ya just need to accept

**Comment by devins2518** [comment]
Alright thanks
